name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: oleksandra-lab-app
          package: .
